on: [workflow_dispatch]

jobs:
  pensar_action_job:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Pensar scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run scan
        uses: pensarai/pensar-local@main
        with:
          language: "ts"
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}